GET http://localhost:3000/api/blogs
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvSWQiOiJGcmFuIiwiY2FkdWNhIjoxNjIwMzE1MTk2LCJpYXQiOjE2MTk0NTExOTZ9.Otc4JL__2dsBAC2_4fRs1Dne3M7IRv-jqG3JZ8APCfc


###
POST http://localhost:3000/api/blogs
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvSWQiOiJGcmFuIiwiY2FkdWNhIjoxNjIwMzE1MTk2LCJpYXQiOjE2MTk0NTExOTZ9.Otc4JL__2dsBAC2_4fRs1Dne3M7IRv-jqG3JZ8APCfc

{
    "nombre":"Mario",
    "titulo": "Busco nevera",
    "categoria": "Electrodomesticos",
    "texto": "Busco nevera de segunda mano"
}


###
POST http://localhost:3000/api/usuarios/registro
Content-Type: application/json

{
    "username": "Fran",
    "email": "francisco@gmail.com",
    "password": "holaMundo4321"
}


###
POST http://localhost:3000/api/usuarios/login
Content-Type: application/json

{
    "email": "francisco@gmail.com",
    "password": "holaMundo4321"
}


###
PUT http://localhost:3000/api/blogs/606eb105b9f54c42843f5b31
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvSWQiOiJGcmFuIiwiY2FkdWNhIjoxNjE4NzY0ODAyLCJpYXQiOjE2MTc5MDA4MDJ9.IbOxQKw6hjML81QApBm_y7MK8_D-OfJD5e_ZWYz7wZg

{
    "nombre": "Francisco",
    "titulo": "Bases de datos",
    "categoria": "Programacion",
    "texto": "Esto es una octava prueba del blog"
}


###
DELETE http://localhost:3000/api/blogs/606f3518d0a15c2d6cc7b537
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvSWQiOiJGcmFuIiwiY2FkdWNhIjoxNjE4NzY0ODAyLCJpYXQiOjE2MTc5MDA4MDJ9.IbOxQKw6hjML81QApBm_y7MK8_D-OfJD5e_ZWYz7wZg